- hosts: all:&provisioned_instance
  become: true
  pre_tasks:
    - name: Set hostname
      become: yes
      hostname:
        name: "{{ ansible_host }}"

    # - name: Disable IPv6 with sysctl
    #   sysctl: name={{ item }} value=1 state=present reload=yes
    #   with_items:
    #     - net.ipv6.conf.all.disable_ipv6
    #     - net.ipv6.conf.default.disable_ipv6
    #     - net.ipv6.conf.lo.disable_ipv6

    # - name: Debian | blacklist ipv6 in modprobe
    #   lineinfile:
    #     dest: /etc/modprobe.d/blacklist.conf
    #     line: 'blacklist ipv6'
    #     mode: '0644'
    #     create: yes
    #   when: ansible_os_family == 'Debian'

    # - name: Uninstall python-backports.ssl-match-hostname
    #   apt:
    #     name: python-backports.ssl-match-hostname
    #     state: absent
    #   when: ansible_os_family == 'Debian'
    #   become: yes

    - name: Install python packages
      become: yes
      apt:
        name:
        - python3-docker
      when: ansible_os_family == 'Debian'

    - name: Install pip
      become: yes
      yum: name=python3-pip
      when: ansible_os_family == 'RedHat'

    - name: Install python modules
      pip:
        executable: pip3
        name:
          - boto3
          - docker
      when: ansible_os_family != 'Debian'

    - name: Upgrade python modules
      pip:
        executable: pip3
        name:
          - awscli
        state: latest
      when: ansible_os_family != 'Debian'

    - include_role:
        name: docker
        apply:
          become: yes


    - name: Run backend-app container
      become: yes
      tags: reload
      docker_container:
        name: backend-app
        image: asia-southeast1-docker.pkg.dev/iac-lab-447109/lab-registry/backend-app:1.2
        restart: yes
        restart_policy: always
        ports:
          - 8080:8080
          - 9464:9464
