- hosts: all:&provisioned_instance
  become: true
  pre_tasks:
    - name: Set hostname
      become: yes
      hostname:
        name: "{{ ansible_host }}"

    - name: Install python packages
      become: yes
      apt:
        name:
        - python3-docker
      when: ansible_os_family == 'Debian'

    - name: Install pip
      become: yes
      yum: name=python3-pip
      when: ansible_os_family == 'RedHat'

    - name: Install python modules
      pip:
        executable: pip3
        name:
          - boto3
          - docker
      when: ansible_os_family != 'Debian'

    - name: Upgrade python modules
      pip:
        executable: pip3
        name:
          - awscli
        state: latest
      when: ansible_os_family != 'Debian'

    - include_role:
        name: docker
        apply:
          become: yes

    - name: Run backend-app container
      become: yes
      tags: reload
      docker_container:
        name: backend-app
        image: asia-southeast1-docker.pkg.dev/iac-lab-447109/lab-registry/backend-app:1.2
        restart: yes
        restart_policy: always
        ports:
          - 8080:8080
          - 9464:9464
