all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_user: {OWNER_NAME}

    provisioned_instance:
      ansible_host: {INSTANCE_IP}
      ansible_user: {OWNER_NAME}
  children:
    backend_app_compute:
