all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_user: nuttapong-r

    provisioned_instance:
      ansible_host: 35.198.245.165
      ansible_user: nuttapong-r
  children:
    backend_app_compute:
