all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_user: {OWNER_NAME}

    provisioned_instance:
      ansible_host: 35.198.245.165
      ansible_user: {OWNER_NAME}
  children:
    backend_app_compute:
